### PR TITLE
Bump plonky2 and replace genesis for checkpoints

### PR DESCRIPTION
**Pull request by Nashtare**
Bumps plonky2 version and replaces `genesis` state root with `checkpoint` state root.
The actual logic of targeting a given `checkpoint` is still to be done within `zero-bin`.

### CODE REVIEW

**Review by BGluth — APPROVED** [review]
Yeah looks good! Actually alsp made a commit that did essentially this yesterday on [assorted_fixes](https://github.com/0xPolygonZero/proof-protocol-decoder/tree/assorted_fixes). There are a handful of fixes on this branch, and for testing, you might want to use this one over main for now if stuff is breaking. I'm planning on merging this back either today or tomorrow once I fix two other bugs that John uncovered with his blocks.

**Comment by Nashtare** [comment]
Actually would you mind if I bump it again to include the kill signal that Zach wanted to integrate to zero-bin to stop worker processes early if one fails? cf https://github.com/0xPolygonZero/plonky2/pull/1429

**Comment by Nashtare** [comment]
Ah right sorry, will close this then as we'll probably merge that branch into main at some point.

**Comment by BGluth** [comment]
Ah no I think this is fine to merge! When I eventually merged `assorted_fixes` back in, it will be easy to just re-base onto this.

**Comment by Nashtare** [comment]
Oki, just reopened :) Also bumped one more time to include the kill-signal logic.

**Pull request merged**
